# Generated by Django 4.2 on 2023-04-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_ucomingmovie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UcomingMovie',
            new_name='UpcomingMovie',
        ),
    ]
