# Generated by Django 4.2 on 2023-04-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_ticket_delete_upcomingmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
