# Generated by Django 4.2 on 2023-04-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('coming_soon', 'Coming Soon'), ('currently_playing', 'Currently Playing')], default='coming_soon', max_length=20),
        ),
    ]
