# Generated by Django 4.2 on 2023-04-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_cast_movie_runtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
