# Generated by Django 4.2 on 2023-04-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_remove_ticket_purchased_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Showing',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
