# Generated by Django 4.2 on 2023-04-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_remove_ticket_showtime_remove_ticket_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='capacity',
        ),
    ]
