# Generated by Django 4.2 on 2023-04-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_remove_theatre_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='shows',
        ),
        migrations.CreateModel(
            name='MovieShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('show_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.showtime')),
            ],
        ),
    ]
