# Generated by Django 4.2 on 2023-04-23 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0014_remove_theatre_shows_movieshowtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_month', models.CharField(max_length=2)),
                ('expiration_year', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DebitCardForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_month', models.CharField(max_length=2)),
                ('expiration_year', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PaypalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.CharField(max_length=20)),
                ('paypal_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tickets', models.IntegerField()),
                ('card_number', models.CharField(max_length=16)),
                ('cvc', models.CharField(max_length=3)),
                ('expiration', models.CharField(max_length=5)),
                ('billing_address', models.CharField(max_length=100)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_method', models.CharField(max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='MovieShowTime',
        ),
        migrations.DeleteModel(
            name='ShowTime',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
    ]
