# Generated by Django 4.2 on 2023-04-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_purchase_showtime_purchase_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='theater',
        ),
    ]
