# Generated by Django 4.2 on 2023-04-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_remove_purchase_showtime_remove_purchase_theater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
