# Generated by Django 4.2 on 2023-04-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_alter_movie_cast_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='watchAgain',
        ),
    ]
