# Generated by Django 4.2 on 2023-04-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_paymentinfo_delete_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
