# Generated by Django 4.2 on 2023-04-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_movieshowing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieShowing',
        ),
    ]
