# Generated by Django 4.2 on 2023-04-29 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_delete_movieshowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='movie',
            name='showtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
