# Generated by Django 4.2 on 2023-04-29 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_remove_movie_url_movie_price_movie_showtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='showtime',
            new_name='showtime_1',
        ),
        migrations.AddField(
            model_name='movie',
            name='showtime_2',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='showtime_3',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='showtime_4',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='showtime_5',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='showtime_6',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
